Add index generation for Pytorch wheels (#777)
This PR adds:

1. The index generation for Pytorch wheels
2. Fix "+" problem in the wheel key link that is omitted in the indexer
3. Improved the modularity of the design with the input parameters

For instance:
"+" sign in the key replaced with the space which causes the error
below:
<Key>gfx94X-dcgpu/torch-2.7.0a0
rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key>

Correct one: 

<Key>gfx94X-dcgpu/torch-2.7.0a0+rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key>

The error seen in the browser:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>gfx94X-dcgpu/torch-2.7.0a0 rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key>
<RequestId>18YCBF52GCKJ14RG</RequestId>
<HostId>45PdRkbM0BsN8/xUq5wj+D9kBFTmn6fu2/F2jbXG8j5BSLU4RPmSAdVCiRFz3EXswfWA/VQwces=</HostId>
</Error>
```

The wheels can we downloaded now from index file:
The index file needs to be refreshed in browser.

https://therock-nightly-python.s3.us-east-2.amazonaws.com/gfx94X-dcgpu/index.html

---------

Co-authored-by: Marius Brehler <marius.brehler@amd.com>

diff --git a/.github/workflows/build_linux_pytorch_wheels.yml b/.github/workflows/build_linux_pytorch_wheels.yml
--- a/.github/workflows/build_linux_pytorch_wheels.yml
+++ b/.github/workflows/build_linux_pytorch_wheels.yml
@@ -12,7 +12,7 @@ on:
       python_version:
         required: true
         type: string
-      find_links:
+      s3_bucket:
         required: true
         type: string
   workflow_dispatch:
@@ -26,7 +26,7 @@ on:
       python_version:
         required: true
         type: string
-      find_links:
+      s3_bucket:
         required: true
         type: string
 
@@ -43,6 +43,8 @@ jobs:
     env:
       OUTPUT_DIR: ${{ github.workspace }}/output
       PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
+      S3_BUCKET: ${{ inputs.s3_bucket }}
+      S3_ENDPOINT: "s3.us-east-2.amazonaws.com"
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -52,9 +54,17 @@ jobs:
           git config --global user.name "therockbot"
           git config --global user.email "therockbot@amd.com"
 
+      - name: Add selected Python version to PATH
+        run: |
+          python_dir="/opt/python/${{ inputs.python_version }}"
+          if ! [ -x "${python_dir}/bin/python" ]; then
+            echo "ERROR: Could not find python: ${python_dir}"
+            exit 1
+          fi
+          echo "${python_dir}/bin" >> "$GITHUB_PATH"
+
       - name: Checkout PyTorch Source Repos
         run: |
-          echo "Checking out PyTorch repositories..."
           ./external-builds/pytorch/pytorch_torch_repo.py checkout
           ./external-builds/pytorch/pytorch_audio_repo.py checkout
           ./external-builds/pytorch/pytorch_vision_repo.py checkout
@@ -67,12 +77,12 @@ jobs:
           echo "Building PyTorch wheels for ${{ inputs.PYTORCH_TARGET_ARCH }}"
           ./external-builds/pytorch/build_prod_wheels.py \
             --pip-cache-dir /tmp/pipcache \
-            --find-links "${{ inputs.find_links }}" \
+            --find-links "https://${{ env.S3_BUCKET }}.s3.us-east-2.amazonaws.com/${{ inputs.AMDGPU_FAMILIES }}/index.html" \
             build \
             --install-rocm \
             --clean \
             --output-dir ${{ env.PACKAGE_DIST_DIR }} \
-            --pytorch-rocm-arch ${{ inputs.PYTORCH_TARGET_ARCH }} \
+            --pytorch-rocm-arch ${{ inputs.PYTORCH_TARGET_ARCH }}
 
       - name: Configure AWS Credentials
         if: always()
@@ -88,6 +98,16 @@ jobs:
       - name: Upload wheels to S3
         if: ${{ github.repository_owner == 'ROCm' }}
         run: |
-          # These wheels share the same S3 directory as rocm-sdk to simplify --find-links usage
-          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://therock-nightly-python/${{ inputs.AMDGPU_FAMILIES }}/ \
+          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/ \
             --recursive --exclude "*" --include "*.whl"
+
+      - name: (Re-)Generate Python package release index
+        if: ${{ github.repository_owner == 'ROCm' }}
+        run: |
+          pip install boto3
+          python ./build_tools/packaging/python/generate_release_index.py \
+            --bucket=${{ env.S3_BUCKET }} \
+            --endpoint=${{ env.S3_ENDPOINT }} \
+            --subdir=${{ inputs.AMDGPU_FAMILIES }} \
+            --output=${{ github.workspace }}/index.html
+          aws s3 cp ${{ github.workspace }}/index.html s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/
