Test

diff --git a/.github/workflows/test_pytorch_wheels.yml b/.github/workflows/test_pytorch_wheels.yml
--- a/.github/workflows/test_pytorch_wheels.yml
+++ b/.github/workflows/test_pytorch_wheels.yml
@@ -55,6 +55,18 @@ jobs:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
+      - name: Add selected Python version to PATH
+        run: |
+          python_dir="/opt/python/${{ inputs.python_version }}"
+          if ! [ -x "${python_dir}/bin/python" ]; then
+            echo "ERROR: Could not find python: ${python_dir}"
+            exit 1
+          fi
+          echo "${python_dir}/bin" >> "$GITHUB_PATH"
+
+          # Ensure /usr/bin/python exists if scripts require it
+          ln -sf "${python_dir}/bin/python3" /usr/bin/python || true
+
       - name: Checkout PyTorch Source Repos
         run: |
           ./external-builds/pytorch/pytorch_torch_repo.py checkout
